# ==========================================
# Rsyslog конфигурация - Ubuntu Server (192.168.10.10)
# Активира UDP приемане на Syslog съобщения от MikroTik маршрутизаторите
# ==========================================

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")
