# ==========================================
# NetBox - пренасочване на порт (Ubuntu Server, 192.168.10.10)
# Стандартен порт 80 е зает от Nextcloud, затова NetBox работи на 8000
# ==========================================

services:
  netbox:
    ports:
      - 8000:8080
